apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpserver
spec:
  replicas: 3
  selector:
    matchLabels:
      app: httpserver
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: httpserver
    spec:
      containers:
        - name: httpserver
          image: server # gcr.io/PROJECT_ID/IMAGE:TAG
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          lifecycle:
            postStart:
              exec:
                command: ['/bin/sh', '-c', 'echo Starting httpserver...']
          readinessProbe: # no need for livenessProbe
            httpGet:
              scheme: HTTP
              path: /healthz
              port: 8080
            initialDelaySeconds: 3
            periodSeconds: 5
          resources:
            requests:
              cpu: 100m
            limits:
              cpu: 100m
          env:
            - name: GRACE_TIMEOUT
              valueFrom:
                configMapKeyRef:
                  name: httpserver-config
                  key: graceTimeout
