apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml
  - configmap.yaml
  - secret.yaml
  # - ingress.yaml
images:
  - name: signormercurio/httpserver
    newTag: 1.5.3
